version: '3'

services:
  pyjtalk:
    build:
      context: .
      dockerfile: Dockerfile
    image: alcnaka/pyjtalk:0.2.0
    volumes:
      - ./pyjtalk:/usr/src/pyjtalk/pyjtalk
      - ./script:/usr/src/pyjtalk/script
      - ./dist:/usr/src/pyjtalk/dist
